OAK-3470: Utils.estimateMemoryUsage has a NoClassDefFoundError when Mongo is not being used
git-svn-id: https://svn.apache.org/repos/asf/jackrabbit/oak/trunk@1724597 13f79535-47bb-0310-9956-ffa450edef68

Former-commit-id: 0ea33a4af2ad9d21bca09044e5042b17319a7a75