OAK-3692 java.lang.NoClassDefFoundError: org/apache/lucene/index/sorter/Sorter$DocComparator
Reverting r1716931 due to baseline failure on CI setup (didn't fail for me though :-/)

git-svn-id: https://svn.apache.org/repos/asf/jackrabbit/oak/trunk@1717234 13f79535-47bb-0310-9956-ffa450edef68

Former-commit-id: df0fc0a97bc3c7f03e9c513e6b27428aa0313853