OAK-3692 java.lang.NoClassDefFoundError: org/apache/lucene/index/sorter/Sorter$DocComparator * Added dependency to lucene-misc for oak-lucene/pom.xml * Add filter for baseline plugin to check o.a.j.o.* only... thus letting go of package changes under lucene (or anything else outside of oak scope)
git-svn-id: https://svn.apache.org/repos/asf/jackrabbit/oak/trunk@1717410 13f79535-47bb-0310-9956-ffa450edef68

Former-commit-id: 4b68df18306091b8aeb53ba30555c02f35ad0266